WITH CITY_TEMPS AS (SELECT 1 AS CITY_CODE, 'Sample City' AS CITY, '2024-01' AS MONTH, 68.0 AS AVG_TEMP_FAHRENHEIT)
SELECT CITY_CODE
     , CITY
     , MONTH
     , {{ to_celcius('AVG_TEMP_FAHRENHEIT') }} AS AVG_TEMP_CELSIUS
 FROM CITY_TEMPS